name: Docker build

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [apache, fpm]
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build the image
        run: |
          docker buildx build \
          --push \
          --platform linux/arm/v7,linux/arm64/v8,linux/amd64,linux/mips64le,linux/ppc64le,linux/s390x,linux/386 \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/eatman:${{ matrix.tag }} \
          -f ./src/docker/${{ matrix.tag }}/Dockerfile .

  create-docker-manifest:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: retag latest image
      run: docker buildx imagetools create ${{ secrets.DOCKERHUB_USERNAME }}/eatman:apache --tag ${{ secrets.DOCKERHUB_USERNAME }}/eatman:latest